name: flutter_application
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  carousel_pro: ^1.0.0
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  firebase_database: ^9.0.4
  cloud_firestore: ^3.1.5
  flutter_typeahead: ^3.2.4
  image_picker: ^0.8.4+4
  otp_text_field: ^1.1.1
  otp_screen: ^0.0.3
  connectivity: ^3.0.6
  carousel_slider: ^4.0.0
  flutter_launcher_icons: ^0.9.2
  geolocator: ^8.0.3
  google_maps_flutter: ^2.1.1
  intl: ^0.17.0
  flutter_local_notifications: ^9.2.0
  flutter_app_badger: ^1.3.0
  url_launcher: ^6.0.18
  google_fonts: ^2.2.0
  timezone: ^0.8.0

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_icons: ^1.1.0
  get: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon.png


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #  - images/a_dot_burr.jpeg
    #  - images/a_dot_ham.jpeg
    - images/app_logo.png
    - assets/supplementimages/cerelac.jpeg
    - assets/supplementimages/farex.jpeg
    - assets/supplementimages/fishoil.jpg
    - assets/supplementimages/lactogen.jpg
    - assets/supplementimages/sarbottam.jpg
    - assets/supplementimages/supravit.jpg
    - assets/supplementimages/ceregrow.jpg
    - assets/supplementimages/cerelac1.jpg
    - assets/supplementimages/dochem.jpg
    - assets/supplementimages/farex1.png
    - assets/supplementimages/lactodex.jpg
    - assets/supplementimages/mamypoko.jpg
    - assets/supplementimages/similac1.png
    - assets/supplementimages/1.jpg
    - assets/supplementimages/2.jpg
    - assets/supplementimages/3.jpg
    - assets/supplementimages/4.jpg
    - assets/supplementimages/5.jpg
    - images/cats/Anti-Hypertensives.jpg
    - images/cats/Anti-Diabetics.jpg
    - images/cats/Peptic-Ulcer-and-Gerd.jpeg
    - images/cats/Minerals-and-Vitamins.jpg
    - images/cats/Antibiotics.jpg
    - images/cats/Opthalmic.jpg
    - images/cats/Anti-Fungal.png
    - images/cats/General-Medicine.png
    - images/cats/Anti-Allergies.jpg
    - images/cats/Lipid-Lowering-Agents.jpg
    - images/cats/Analgesics.png
    - images/cats/Anti-Asthmatic.jpg
    - images/cats/Cough-and-Cold.jpg
    - images/cats/Laxatives.jpg
    - images/cats/Ear-Drops.jpg
    - images/cats/Digestive-Enzymes.jpg
    - images/cats/Thyrodism.jpg
    - images/cats/Nasal.jpg
    - images/cats/Anti-Cold.jpg
    - images/cats/Diuretics.png
    - images/cats/Pre-and-Probiotic.png
    - images/cats/Anti-Platelet.jpg
    - images/cats/Urology-Medicine.png
    - images/cats/Anti-Coagulant.jpg
    - images/cats/Neuropathic-Pain.jpeg
    - images/cats/Anti-Spasmodic.jpeg
    - images/cats/Anti-Fibrinolytic.png
    - images/cats/Anti-Depressants.jpg
    - images/cats/Anti-Emetic.png
    - images/cats/Anti-hyperuricemic.png
    - images/cats/Dermatology-Medicine.jpg
    - images/cats/Anti-Psychotics.png
    - images/cats/Anti-Convulsant.jpg
    - images/cats/Benzodiazepines.jpg
    - images/cats/Alpha-blockers.png

    - images/products/medicine1.jpg
    - images/products/medicine2.jpg
    - images/products/medicine3.jpg
    - images/products/medicine4.jpg
    - images/products/medicine5.jpg
    - images/products/medicine6.jpg

    - assets/medicineimages/Decold.jpg
    - assets/medicineimages/Nims.jpg
    - assets/medicineimages/Rhinex.jpg
    - assets/medicineimages/Sancho.jpg
    - assets/medicineimages/Sinex.jpg
    - assets/medicineimages/TusQD.png

    - assets/supplementimages/groviva.jpg
    - assets/supplementimages/maxvida.jpg
    - assets/supplementimages/pediasure.jpeg
    - assets/supplementimages/protineX.jpg
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages